package com.mobile.healthypets.api.lab;

public class JSONLabCreate {
	public Long idHewan;
	public Long idResepsionis;
	public Long idAmbulator;
	public String k_parasit;
	public String k_jamur;
	public String keadaan_feses;
	public String p_interna;
	public String protozoa;
	public String mikroba;
	public String warna;
	public String bau;
	public String uji_gula;
	public String uji_protein;
	public String uji_sedimentasi;
	public String warna_darah;
	public String sifat_darah;
	public String natif_protozoa;
	public String natif_bakteri;
	public String bdm;
	public String bdp;
	public String netrofil;
	public String eosinofil;
	public String basofil;
	public String limfosit;
	public String monosit;
	public String stab;
	public String hb;
	public String ht;
	public String diagnosa;
	public String dif_diag;
	public String prognosa;
	public String terapi;
	public String drh_jaga;
	public String tgl;
	public String kode_hewan;
	public Long idAmb;
}
